server {
    listen 80;

    # Sirve el HTML
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Redirige las llamadas /api/ al backend
    location /api/ {
        proxy_pass http://backend:8080/api/;
        client_max_body_size 50M;
    }
}